name: clojure-test

services:
  appserver:
    type: compose

    services:
      image: acobster/lando-clojure:lein
      command: lein ring server-headless

      ports:
        - '9001'
        - '3000'

tooling:
  lein:
    service: appserver
    cmd: lein

proxy:
  appserver:
    - clojure-test.lndo.site
