name: lando-clojure-test
recipe: custom
config:
  webroot: .

services:
  appserver:
    type: compose

    services:
      image: clojure:openjdk-8-lein

      command: lein ring server-headless

tooling:
  lein:
    service: appserver
    cmd: lein
