name: clojure-test

services:
  appserver:
    type: compose

    services:
      image: acobster/lando-clojure:lein
      command: lein ring server-headless

tooling:
  lein:
    service: appserver
    cmd: lein

  repl:
    service: appserver
    cmd: lein repl

  test:
    service: appserver
    cmd: lein test

proxy:
  appserver:
    - clojuretest.lndo.site:3000
