name: lando-clojure-test
config:
  webroot: .

services:
  appserver:
    type: compose

    services:
      image: acobster/lando-clojure:stable
      command: lein

    overrides:
      environment:
        LEIN_NREPL_HOST: 0.0.0.0

    run_as_root:
      - lein deps
      - lein

tooling:
  lein:
    service: appserver
    cmd: lein

  repl:
    service: appserver
    cmd: lein repl :start
